services:
  web:
    container_name: gunicorn
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 --reload wsgi:app
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ../:/workspace:cached
    networks:
      - reddit-network
    environment:
      - REDDIT_USER
      - REDDIT_USER_PASSWORD
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - USER_AGENT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - OPENAI_API_KEY
      - OPENAI_ENCODER
      - OPENAI_EMBEDDING_MODEL
      - OPENAI_EMBEDDING_MODEL_TOKEN_LIMIT
      - CHUNK_SIZE
      - CHUNK_OVERLAP

  db:
    container_name: postgres
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - reddit-network
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

networks:
  reddit-network:
    name: reddit-network

volumes:
  postgres-data:
    name: rag-reddit_postgres-data