services:
  db:
    container_name: postgres-reddit-dev
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    env_file: ../.env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  
volumes:  
  postgres-data: