services:
  web:
    container_name: gunicorn
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 --reload wsgi:app
    ports:
      - 5000:5000
    env_file:
      - ../.env.prod
    depends_on:
      - db
    volumes:
      - ../:/workspace:cached
    networks:
      - reddit-network

  db:
    container_name: postgres
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    env_file:
      - ../.env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - reddit-network

networks:
  reddit-network:
    name: reddit-network

volumes:
  postgres-data:
    name: rag-reddit_postgres-data