FROM python:3.11.3-slim-buster

WORKDIR /workspace

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install

# install dependencies
RUN pip install --upgrade pip
COPY requirements.txt /workspace/requirements.txt
RUN pip install -r requirements.txt
