services:
  python:
    container_name: python-dev
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - ../:/workspace:cached
    working_dir: /workspace
    command: /bin/bash -c "pip install --upgrade pip && pip install -r requirements.txt && sleep infinity"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - reddit-network-dev

  db:
    container_name: postgres-dev
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - reddit-network-dev

networks:
  reddit-network-dev:
    name: reddit-network-dev

volumes:
  postgres-data:
    name: reddit_stack_postgres-data-dev