services:
  web:
    container_name: flask-reddit-dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    ports:
      - 8000:8000
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
      - ../:/workspace:cached
    networks:
      - reddit-network-dev

  db:
    container_name: postgres-dev
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - reddit-network-dev

networks:
  reddit-network-dev:
    name: reddit-network-dev

volumes:
  postgres-data:
    name: reddit_stack_postgres-data-dev