name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          if [ -d "/app" ]; then
            cd /app
            git fetch origin main
            git reset --hard origin/main
          else
            mkdir -p /app
            git clone https://github.com/LorenzoPeve/rag-reddit.git /app
            cd /app
          fi
          
          # Stop existing containers
          docker compose -f docker/docker-compose.prod.yml -p rag-reddit down

          # Create .env file from GitHub secrets
          cat > .env.prod << EOL
          REDDIT_USER=${{ secrets.REDDIT_USER }}
          REDDIT_USER_PASSWORD=${{ secrets.REDDIT_USER_PASSWORD }}
          REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }}
          USER_AGENT=${{ secrets.USER_AGENT }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_ENCODER=cl100k_base
          OPENAI_EMBEDDING_MODEL=text-embedding-3-small
          OPENAI_EMBEDDING_MODEL_TOKEN_LIMIT=8191
          CHUNK_SIZE=1200
          CHUNK_OVERLAP=120
          EOL

          # Build and start containers with the new env file
          docker compose -f docker/docker-compose.prod.yml -p rag-reddit up -d --build